---
- hosts: localhost
  vars:
    image_id: ami-011c99152163a87ae
    aws_instance_type: "t2.micro"
    ec2_count: 1
  variables_file: './dev.tfvars'

  vars_files:
    - './vars/external_vars.yaml'
  tasks:
    - name: Run Terraform scripts and defining backend configurations
      community.general.terraform:
        project_path: './'
        state: "{{ instance_state }}"
        force_init: true
        backend_config:
          bucket: '{{ s3_bucket }}'
          key: '{{ state_key }}'
          region: '{{ aws_region }}'
        # variables:
        #   ami_id: "{{ image_id }}"
        #   instance_type: "{{ aws_instance_type }}"
        #   ec2_count: "{{ ec2_count }}"
        variables_file:  
          - "{{ variables_file }}"